export const environmentalKpis = [
  {
    id: 'emissions',
    title: 'Total Carbon Emissions',
    value: '18,240',
    unit: 'kg CO2',
    delta: '▲ 5%',
    deltaTone: 'warning',
    caption: 'Compared to last month',
    icon: 'leaf',
  },
  {
    id: 'reduction',
    title: 'Emission Reduction',
    value: '-12%',
    delta: 'On track',
    deltaTone: 'success',
    caption: 'Compared to baseline',
    icon: 'arrow',
  },
  {
    id: 'goals',
    title: 'Active Sustainability Goals',
    value: '18',
    delta: '3 due',
    deltaTone: 'primary',
    caption: '3 due this month',
    icon: 'target',
  },
  {
    id: 'completion',
    title: 'Goal Completion Rate',
    value: '82%',
    progress: 82,
    caption: 'Across all departments',
    icon: 'progress',
  },
];

export const emissionTrendData = [
  { period: 'Jan', emissions: 1720, target: 1650 },
  { period: 'Feb', emissions: 1680, target: 1610 },
  { period: 'Mar', emissions: 1610, target: 1580 },
  { period: 'Apr', emissions: 1560, target: 1540 },
  { period: 'May', emissions: 1490, target: 1510 },
  { period: 'Jun', emissions: 1450, target: 1480 },
  { period: 'Jul', emissions: 1510, target: 1450 },
  { period: 'Aug', emissions: 1485, target: 1420 },
  { period: 'Sep', emissions: 1430, target: 1400 },
  { period: 'Oct', emissions: 1390, target: 1370 },
  { period: 'Nov', emissions: 1345, target: 1340 },
  { period: 'Dec', emissions: 1280, target: 1310 },
];

export const departmentRanking = [
  { name: 'Manufacturing', emissions: 5200 },
  { name: 'Logistics', emissions: 4300 },
  { name: 'Sales', emissions: 2100 },
  { name: 'HR', emissions: 1200 },
  { name: 'Finance', emissions: 800 },
];

export const environmentalGoals = [
  {
    id: 'GOAL-1001',
    name: 'Reduce Fleet Emissions',
    department: 'Logistics',
    target: '2,000 kg',
    current: '2,400 kg',
    progress: 80,
    deadline: '30 Sep 2026',
    status: 'Active',
    owner: 'Maya Carter',
    priority: 'High',
    comments: 6,
    attachments: 3,
    timeline: [
      { label: 'Baseline approved', date: '12 Jan 2026', status: 'done' },
      { label: 'Route optimization deployed', date: '02 Apr 2026', status: 'done' },
      { label: 'EV transition review', date: '18 Aug 2026', status: 'current' },
      { label: 'Quarterly verification', date: '30 Sep 2026', status: 'upcoming' },
    ],
    activity: [
      { user: 'Maya Carter', action: 'Updated progress to 80%', time: '2 hours ago' },
      { user: 'Daniel Kim', action: 'Uploaded logistics emissions file', time: 'Yesterday' },
      { user: 'Sustainability Office', action: 'Requested verification evidence', time: '3 days ago' },
    ],
    attachmentsList: ['fleet-baseline.xlsx', 'route-optimization.pdf', 'supplier-fuel-log.csv'],
  },
  {
    id: 'GOAL-1002',
    name: 'Zero Waste to Landfill',
    department: 'Manufacturing',
    target: '0 kg',
    current: '380 kg',
    progress: 45,
    deadline: '14 Jul 2026',
    status: 'Overdue',
    owner: 'Noah Bennett',
    priority: 'High',
    comments: 4,
    attachments: 2,
    timeline: [
      { label: 'Waste audit completed', date: '04 Feb 2026', status: 'done' },
      { label: 'Vendor onboarding', date: '12 May 2026', status: 'done' },
      { label: 'Recycling line launch', date: '01 Jul 2026', status: 'current' },
      { label: 'Final review', date: '14 Jul 2026', status: 'overdue' },
    ],
    activity: [
      { user: 'Noah Bennett', action: 'Marked milestone at risk', time: '4 hours ago' },
      { user: 'Ana Perez', action: 'Added landfill diversion contract', time: '1 day ago' },
    ],
    attachmentsList: ['waste-audit.pdf', 'vendor-contract.docx'],
  },
  {
    id: 'GOAL-1003',
    name: '100% Renewable Electricity',
    department: 'Facilities',
    target: '100%',
    current: '100%',
    progress: 100,
    deadline: '31 Mar 2026',
    status: 'Completed',
    owner: 'Elena Rossi',
    priority: 'Medium',
    comments: 8,
    attachments: 5,
    timeline: [
      { label: 'Supplier tender', date: '12 Jan 2026', status: 'done' },
      { label: 'Contract signed', date: '09 Mar 2026', status: 'done' },
      { label: 'Meter validation', date: '31 Mar 2026', status: 'done' },
    ],
    activity: [
      { user: 'Elena Rossi', action: 'Closed goal as completed', time: '1 week ago' },
      { user: 'Procurement Team', action: 'Attached supplier certificate', time: '2 weeks ago' },
    ],
    attachmentsList: ['ppa-contract.pdf', 'renewable-certificate.pdf', 'meter-validation.xlsx'],
  },
  {
    id: 'GOAL-1004',
    name: 'Paperless Office Rollout',
    department: 'HR',
    target: '90%',
    current: '68%',
    progress: 68,
    deadline: '18 Nov 2026',
    status: 'Active',
    owner: 'Liam Foster',
    priority: 'Low',
    comments: 2,
    attachments: 1,
    timeline: [
      { label: 'Policy launched', date: '20 Feb 2026', status: 'done' },
      { label: 'Training sessions', date: '08 Jun 2026', status: 'current' },
      { label: 'Department adoption review', date: '18 Nov 2026', status: 'upcoming' },
    ],
    activity: [{ user: 'Liam Foster', action: 'Shared adoption snapshot', time: '5 days ago' }],
    attachmentsList: ['paperless-adoption.png'],
  },
  {
    id: 'GOAL-1005',
    name: 'Travel Emissions Policy Update',
    department: 'Sales',
    target: '1,100 kg',
    current: '980 kg',
    progress: 89,
    deadline: '10 Oct 2026',
    status: 'Active',
    owner: 'Priya Shah',
    priority: 'Medium',
    comments: 3,
    attachments: 2,
    timeline: [
      { label: 'Travel baseline approved', date: '15 Jan 2026', status: 'done' },
      { label: 'Policy circulated', date: '20 Mar 2026', status: 'done' },
      { label: 'Adoption measurement', date: '10 Oct 2026', status: 'current' },
    ],
    activity: [{ user: 'Priya Shah', action: 'Requested regional exception review', time: '2 days ago' }],
    attachmentsList: ['travel-policy-v3.pdf', 'regional-adoption.csv'],
  },
  {
    id: 'GOAL-1006',
    name: 'Supplier Packaging Reduction',
    department: 'Procurement',
    target: '25%',
    current: '12%',
    progress: 48,
    deadline: '15 Dec 2026',
    status: 'Draft',
    owner: 'Jonas Weber',
    priority: 'Medium',
    comments: 1,
    attachments: 0,
    timeline: [
      { label: 'Scope definition', date: '01 Jul 2026', status: 'current' },
      { label: 'Pilot launch', date: '15 Sep 2026', status: 'upcoming' },
    ],
    activity: [{ user: 'Jonas Weber', action: 'Created draft workflow', time: '1 week ago' }],
    attachmentsList: [],
  },
  {
    id: 'GOAL-1007',
    name: 'Water Reuse Program',
    department: 'Manufacturing',
    target: '1,500 m3',
    current: '1,020 m3',
    progress: 74,
    deadline: '22 Dec 2026',
    status: 'Active',
    owner: 'Camila Ortiz',
    priority: 'High',
    comments: 5,
    attachments: 4,
    timeline: [
      { label: 'Feasibility approved', date: '12 Mar 2026', status: 'done' },
      { label: 'Equipment installation', date: '28 Jul 2026', status: 'current' },
      { label: 'Compliance audit', date: '22 Dec 2026', status: 'upcoming' },
    ],
    activity: [{ user: 'Camila Ortiz', action: 'Logged installation progress', time: 'Yesterday' }],
    attachmentsList: ['water-reuse-capex.xlsx', 'site-layout.pdf'],
  },
  {
    id: 'GOAL-1008',
    name: 'Office Energy Intensity Reduction',
    department: 'Finance',
    target: '15%',
    current: '9%',
    progress: 60,
    deadline: '28 Nov 2026',
    status: 'Active',
    owner: 'Owen Lee',
    priority: 'Low',
    comments: 2,
    attachments: 1,
    timeline: [
      { label: 'Metering installed', date: '30 Apr 2026', status: 'done' },
      { label: 'HVAC tuning', date: '16 Aug 2026', status: 'current' },
      { label: 'Energy audit closeout', date: '28 Nov 2026', status: 'upcoming' },
    ],
    activity: [{ user: 'Owen Lee', action: 'Added updated energy audit', time: '6 days ago' }],
    attachmentsList: ['energy-audit.pdf'],
  },
];

export const transactions = [
  {
    id: 'TRX-2101',
    date: '12 Jul 2026',
    department: 'Logistics',
    source: 'Fleet',
    quantity: '500 L',
    factor: '2.31',
    co2Generated: '1,155 kg',
    status: 'Verified',
  },
  {
    id: 'TRX-2102',
    date: '11 Jul 2026',
    department: 'Manufacturing',
    source: 'Electricity',
    quantity: '1,200 kWh',
    factor: '0.45',
    co2Generated: '540 kg',
    status: 'Pending',
  },
  {
    id: 'TRX-2103',
    date: '10 Jul 2026',
    department: 'Sales',
    source: 'Travel',
    quantity: '1,500 km',
    factor: '0.12',
    co2Generated: '180 kg',
    status: 'Verified',
  },
  {
    id: 'TRX-2104',
    date: '09 Jul 2026',
    department: 'Facilities',
    source: 'Electricity',
    quantity: '890 kWh',
    factor: '0.45',
    co2Generated: '401 kg',
    status: 'Pending',
  },
  {
    id: 'TRX-2105',
    date: '08 Jul 2026',
    department: 'HR',
    source: 'Waste',
    quantity: '200 kg',
    factor: '0.85',
    co2Generated: '170 kg',
    status: 'Draft',
  },
  {
    id: 'TRX-2106',
    date: '07 Jul 2026',
    department: 'Finance',
    source: 'Travel',
    quantity: '650 km',
    factor: '0.12',
    co2Generated: '78 kg',
    status: 'Verified',
  },
];

export const emissionSources = [
  { name: 'Fleet', value: 4500, color: '#2E7D32' },
  { name: 'Manufacturing', value: 5200, color: '#1976D2' },
  { name: 'Electricity', value: 3100, color: '#0F766E' },
  { name: 'Travel', value: 1200, color: '#F59E0B' },
  { name: 'Waste', value: 800, color: '#DC2626' },
];

export const quickActions = [
  'Create Goal',
  'Add Carbon Transaction',
  'Import Emission Data',
  'Generate Carbon Report',
  'Configure Emission Factors',
];

export function getGoalSummary(goals) {
  return [
    {
      label: 'Goals Completed',
      value: goals.filter((goal) => goal.status === 'Completed').length,
      tone: 'success',
    },
    {
      label: 'Goals In Progress',
      value: goals.filter((goal) => goal.status === 'Active').length,
      tone: 'primary',
    },
    {
      label: 'Goals Overdue',
      value: goals.filter((goal) => goal.status === 'Overdue').length,
      tone: 'danger',
    },
    {
      label: 'Upcoming Deadlines',
      value: goals.filter((goal) => goal.status === 'Active' || goal.status === 'Draft').length,
      tone: 'warning',
    },
  ];
}
